name: Sync Artwork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS  }}
  IMAGES_SPREADSHEET_ID: ${{ secrets.IMAGES_SPREADSHEET_ID }}
  EVENTS_SPREADSHEET_ID: ${{ secrets.EVENTS_SPREADSHEET_ID }}
  ARTWORK_IMAGES_FOLDER_ID: ${{ secrets.ARTWORK_IMAGES_FOLDER_ID }}
  HOSTINGER_FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}
  HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
  HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
  HOSTINGER_FTP_PORT: ${{ secrets.HOSTINGER_FTP_PORT }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
        
      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Sync Gallery
        run: python syncgallery.py

      - name: Sync Events
        run: python syncevents.py

      